---
title: "jupyter_remote_config"
author: "Lincoln Harris"
date: "4/4/2018"
output: html_document
---

*Instructions for how to run Jupyter Notebook from a virtual machine*  

**If you are using a virtual machine that already has Jupyter Notebook, you can ignore steps 1-8**

*1.* Dwld anaconda to the instance        
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`wget https://repo.continuum.io/archive/Anaconda3-4.2.0-Linux-x86_64.sh`       

*2.* Install anaconda        
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`bash Anaconda3-4.2.0-Linux-x86_64.sh`      
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ENTER to confirm location        
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'yes' to prepend install location to path       

*3.* Check that anaconda is in the preferred environment        
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`which python` should return:         
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`/home/ubuntu/anaconda3/bin/python`       

*4.* Create a password for jupyter notebook       
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ipython:         
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`from IPython.lib import passwd`        
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`passwd()`        
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*make sure to grab keypair!!*       
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`exit`        

*5.* Create config profile       
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`jupyter notebook --generate-config`       

*6.* Create certificates for https       
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`mkdir jupyterCerts`       
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`cd jupyterCerts`       
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`sudo openssl req -x509 -nodes -days 365 -newkey rsa:1024 -keyout mycert.pem -out mycert.pem`      
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;answer questions     

*7.* Configure jupyter     
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`cd ~/.jupyter/`       
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`vi jupyter_notebook_config.py`      
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;	add the following chunk:     

	`c = get_config()

	# Kernel config
	c.IPKernelApp.pylab = 'inline'  # if you want plotting support always in your notebook

	# Notebook config
	c.NotebookApp.certfile = u'/home/ubuntu/certs/mycert.pem' #location of your certificate file
	c.NotebookApp.ip = '*'
	c.NotebookApp.open_browser = False  #so that the ipython notebook does not opens up a browser by default
	c.NotebookApp.password = u'sha1:98ff0e580111:12798c72623a6eecd54b51c006b1050f0ac1a62d'  #the encrypted password we generated above
	# Set the port to 8888, the port we set up in the AWS EC2 set-up
	c.NotebookApp.port = 8888`

*8.* Exit ssh session      

*9.* Login to new session with the following:          
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`ssh -i /Users/lincoln.harris/AWS_config_and_installs/Lincoln.harris-1.pem -L 8157:127.0.0.1:8888 ubuntu@ec2-###-##-##-###.compute-1.amazonaws.com`        

*10.* Start the jupyter server          
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`jupyter notebook`        

*11.* Navigate to        
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;https://127.0.0.1:8157           

*12.* Edit away!!        
 
**if local port (8157) is busy:**         
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;check       
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`lsof -ti:8157`         
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;kill process           
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`lsof -ti:8157 | xargs kill -9`    

	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;you should be able to proceed as normal after this        
