---
title: "mountVolume"
author: "Lincoln Harris"
date: "5/23/2018"
output: html_document
---

*Instructions for how to mount an additional volume to an AMI*

*1.* After volume has been attached via web console:       
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;list available block devices        
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`lsblk`         

*2.* Check to see if volume is empty or not       
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`sudo file -s /dev/xvdf`         
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;should return:        
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`/dev/xvdf: data`        

*3.* Format the volume's filesystem         
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`sudo mkfs -t ext4 /dev/xvdf`        

*4.* Make a new root directory to store volume      
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`sudo mkdir /myVolume`      

*5.* Mount the volume       
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`sudo mount /dev/xvdf /myVolume/`       

*6.* Display available space in new volume        
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`df -h /myVolume`         